// <auto-generated />
using Case.Infra.Data.Sql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Case.Infra.Data.Sql.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20251112034248_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Case.Infra.Data.Sql.Entities.ChassisId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<string>("Series")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChassisId");
                });

            modelBuilder.Entity("Case.Infra.Data.Sql.Entities.VehiclesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChassisIdId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("PassengersNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ChassisIdId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Case.Infra.Data.Sql.Entities.VehiclesEntity", b =>
                {
                    b.HasOne("Case.Infra.Data.Sql.Entities.ChassisId", "ChassisId")
                        .WithMany()
                        .HasForeignKey("ChassisIdId");

                    b.Navigation("ChassisId");
                });
#pragma warning restore 612, 618
        }
    }
}
